export default {
  SYSTEM_SET_SELECTED_DEVICE_ID: 'SYSTEM_SET_SELECTED_DEVICE_ID',
  SYSTEM_SET_OPENED_CHANEL: 'SYSTEM_SET_OPENED_CHANEL',
  SYSTEM_SET_DEVICE_STATUS: 'SYSTEM_SET_DEVICE_STATUS',
  SYSTEM_SET_CONFIRMED_PASSWORD: 'SYSTEM_SET_CONFIRMED_PASSWORD',

  SYSTEM_SET_COMMAND_RESPONSE: 'SYSTEM_SET_COMMAND_RESPONSE'
}