export default {
  WEB_SOCKET_CONNECTED: 'WEB_SOCKET_CONNECTED',
  WEB_SOCKET_DISCONNECTED: 'WEB_SOCKET_DISCONNECTED',
  WEB_SOCKET_ERROR_CONNECTION: 'WEB_SOCKET_ERROR_CONNECTION',
  WEB_SOCKET_ERROR: 'WEB_SOCKET_ERROR',

  TCP_CONNECTED: 'TCP_CONNECTED',
  TCP_DISCONNECTED: 'TCP_DISCONNECTED',
  TCP_RESPONSE: 'TCP_RESPONSE',
}
