import keyMirror from 'keymirror';

export default keyMirror({

  SET_NOTES: 'SET_NOTES',
  SET_NOTES_ERROR: 'SET_NOTES_ERROR',
  CREATE_NOTE: 'CREATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',


  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  KEY_CODE: {

  }
});