export default {
  DEVICES_OPEN_MODAL: 'DEVICES_OPEN_MODAL',
  DEVICES_CLOSE_MODAL: 'DEVICES_CLOSE_MODAL',

  DEVICES_SET_CONNECT_PROGRESS: 'DEVICES_SET_CONNECT_PROGRESS',

  DEVICES_START_GET: 'DEVICES_START_GET',
  DEVICES_STOP_GET: 'DEVICES_STOP_GET',

  DEVICES_SET_SERVER_RES: 'DEVICES_SET_SERVER_RES',
  DEVICES_SET_IDS: 'DEVICES_SET_IDS',
}